logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
server:
  port: 8081
  servlet:
    context-path: /formulario/v1
spring:
  data:
    mongodb:
      database: db_easyquality_form
      host: localhost
      port: 27017
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 5
      transaction-id-prefix: logs-events-formulario-done
      
custonKafka:
  loggin:
    questionatio:
      topic: topic-logs-events-formulario-done     
    
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
