---
apiVersion: v1
kind: Service
metadata:
  name: questionario
  namespace: conformidade
  labels:
    app: questionario
spec:
  type: NodePort
  ports:
  - name: web
    port: 8080
    #targetPort: 8080
    nodePort: 30089
    protocol: TCP    
  selector:
    app: questionario
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: questionario
  namespace: conformidade
  labels:
    app: questionario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: questionario
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: questionario 
    spec:
      containers:
      - name: questionario-api
        resources:
          limits:
            memory: "500Mi"
            cpu: "300m"
          requests:
            memory: "300Mi"
            cpu: "200m"
        image: registry.stelo.intranet:5000/api-questionario:demo
        env :
        - Nome : ENV_DATABASE
          valueFrom :
            configMapKeyRef : 
              Nome : configmaps-questionario.database
              chave : mongodb.database
        - Nome : ENV_DATABASE_HOST
          valueFrom :
            configMapKeyRef : 
              Nome : configmaps-questionario.database.host
              chave : mongodb.database.host
        - Nome : ENV_DATABASE_PORT
          valueFrom :
            configMapKeyRef : 
              Nome : configmaps-questionario.database.port
              chave : mongodb.database.port
        - Nome : ENV_KAFKA_BOOTSTRAP_SERVER
          valueFrom :
            configMapKeyRef : 
              Nome : configmaps-kafka-bootstrap-servers
              chave : kafka.bootstrap.servers

        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP    
        readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            failureThreshold: 1
            periodSeconds: 1
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            failureThreshold: 1
            initialDelaySeconds: 8
            periodSeconds: 1