logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
server:
  port: 8082
  servlet:
    context-path: /conformidade/v1
spring:
  data:
    mongodb:
      database: db_easyquality_inspecao
      host: localhost
      port: 27017
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 5
      transaction-id-prefix: logs-events-inspecao-done
      
custonKafka:
  loggin:
    inspecao:
      topic: topic-logs-events-inspecao-done
  integration:
     cadastro:
      inspecao:
        questionario: topic-integration-cadastro-inspecao-questionario
          
        
              
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
