logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
server:
  port: 8082
  servlet:
    context-path: /conformidade/v1
spring:
  data:
    mongodb:
      database: db_easyquality_form
      host: localhost
      port: 27017
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 5
      transaction-id-prefix: logs-events-formulario-done
    consumer:
      bootstrap-servers: localhost:9092
      groupId: group-integration-cadastro-inspecao-questionario
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: org.apache.kafka.common.serialization.StringSerializer
      autoOffsetReset: earliest
      enableAutoCommit: false
      isolationLevel: read-committed
    listener:
      ackMode: MANUAL  
      
custonKafka:
  loggin:
    questionatio:
      topic: topic-logs-events-formulario-done
  integration:
     cadastro:
      inspecao:
        questionario: topic-integration-cadastro-inspecao-questionario
        questionario-enriquecido: topic-integration-cadastro-inspecao-questionario-enriquecido     
           
    
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
